Search.appendIndex(
    [
                {
            "fqsen": "\\App\\Controllers\\Auth",
            "name": "Auth",
            "summary": "Authentication\u0020Controller.",
            "url": "classes/App-Controllers-Auth.html"
        },                {
            "fqsen": "\\App\\Controllers\\Auth\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "Construct\u0020UsersModel.",
            "url": "classes/App-Controllers-Auth.html#method___construct"
        },                {
            "fqsen": "\\App\\Controllers\\Auth\u003A\u003Aindex\u0028\u0029",
            "name": "index",
            "summary": "Shows\u0020login\u0020page\u0020and\u0020its\u0020form.",
            "url": "classes/App-Controllers-Auth.html#method_index"
        },                {
            "fqsen": "\\App\\Controllers\\Auth\u003A\u003A_login\u0028\u0029",
            "name": "_login",
            "summary": "Validate\u0020login\u0020form,\u0020sending\u0020email\u0020through\u0020post\u0020form\nand\u0020verify\u0020password.",
            "url": "classes/App-Controllers-Auth.html#method__login"
        },                {
            "fqsen": "\\App\\Controllers\\Auth\u003A\u003A_logout\u0028\u0029",
            "name": "_logout",
            "summary": "",
            "url": "classes/App-Controllers-Auth.html#method__logout"
        },                {
            "fqsen": "\\App\\Controllers\\Auth\u003A\u003AforgetPassword\u0028\u0029",
            "name": "forgetPassword",
            "summary": "",
            "url": "classes/App-Controllers-Auth.html#method_forgetPassword"
        },                {
            "fqsen": "\\App\\Controllers\\Auth\u003A\u003A_forgetPassword\u0028\u0029",
            "name": "_forgetPassword",
            "summary": "",
            "url": "classes/App-Controllers-Auth.html#method__forgetPassword"
        },                {
            "fqsen": "\\App\\Controllers\\Auth\u003A\u003AresetPassword\u0028\u0029",
            "name": "resetPassword",
            "summary": "",
            "url": "classes/App-Controllers-Auth.html#method_resetPassword"
        },                {
            "fqsen": "\\App\\Controllers\\Auth\u003A\u003A_resetPassword\u0028\u0029",
            "name": "_resetPassword",
            "summary": "",
            "url": "classes/App-Controllers-Auth.html#method__resetPassword"
        },                {
            "fqsen": "\\App\\Controllers\\Auth\u003A\u003AverifyEmail\u0028\u0029",
            "name": "verifyEmail",
            "summary": "",
            "url": "classes/App-Controllers-Auth.html#method_verifyEmail"
        },                {
            "fqsen": "\\App\\Controllers\\Auth\u003A\u003A_verifyPassword\u0028\u0029",
            "name": "_verifyPassword",
            "summary": "",
            "url": "classes/App-Controllers-Auth.html#method__verifyPassword"
        },                {
            "fqsen": "\\App\\Controllers\\Auth\u003A\u003A_setSession\u0028\u0029",
            "name": "_setSession",
            "summary": "",
            "url": "classes/App-Controllers-Auth.html#method__setSession"
        },                {
            "fqsen": "\\App\\Controllers\\Auth\u003A\u003A\u0024um",
            "name": "um",
            "summary": "",
            "url": "classes/App-Controllers-Auth.html#property_um"
        },                {
            "fqsen": "\\App\\Controllers\\BaseController",
            "name": "BaseController",
            "summary": "Class\u0020BaseController",
            "url": "classes/App-Controllers-BaseController.html"
        },                {
            "fqsen": "\\App\\Controllers\\BaseController\u003A\u003AinitController\u0028\u0029",
            "name": "initController",
            "summary": "Constructor.",
            "url": "classes/App-Controllers-BaseController.html#method_initController"
        },                {
            "fqsen": "\\App\\Controllers\\BaseController\u003A\u003A\u0024request",
            "name": "request",
            "summary": "Instance\u0020of\u0020the\u0020main\u0020Request\u0020object.",
            "url": "classes/App-Controllers-BaseController.html#property_request"
        },                {
            "fqsen": "\\App\\Controllers\\BaseController\u003A\u003A\u0024helpers",
            "name": "helpers",
            "summary": "An\u0020array\u0020of\u0020helpers\u0020to\u0020be\u0020loaded\u0020automatically\u0020upon\nclass\u0020instantiation.\u0020These\u0020helpers\u0020will\u0020be\u0020available\nto\u0020all\u0020other\u0020controllers\u0020that\u0020extend\u0020BaseController.",
            "url": "classes/App-Controllers-BaseController.html#property_helpers"
        },                {
            "fqsen": "\\App\\Controllers\\Content\\History",
            "name": "History",
            "summary": "This\u0020controller\u0020provides\u0020content\u0020management\u0020controller\u0020for\u0020displaying\u0020contents\u0020in\u0020host\/sejarah\u0020route.",
            "url": "classes/App-Controllers-Content-History.html"
        },                {
            "fqsen": "\\App\\Controllers\\Content\\History\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "Prepare\u0020HistoryModel.",
            "url": "classes/App-Controllers-Content-History.html#method___construct"
        },                {
            "fqsen": "\\App\\Controllers\\Content\\History\u003A\u003Aindex\u0028\u0029",
            "name": "index",
            "summary": "Create\u0020form\u0020view\u0020of\u0020History\u0020Content.",
            "url": "classes/App-Controllers-Content-History.html#method_index"
        },                {
            "fqsen": "\\App\\Controllers\\Content\\History\u003A\u003A_updateHistory\u0028\u0029",
            "name": "_updateHistory",
            "summary": "Crud\u0020form\u0020validation\u0020for\u0020History\u0020Content.",
            "url": "classes/App-Controllers-Content-History.html#method__updateHistory"
        },                {
            "fqsen": "\\App\\Controllers\\Content\\History\u003A\u003A\u0024hm",
            "name": "hm",
            "summary": "HistoryModel\u0020initiator.",
            "url": "classes/App-Controllers-Content-History.html#property_hm"
        },                {
            "fqsen": "\\App\\Controllers\\Content\\OrganizationProfile",
            "name": "OrganizationProfile",
            "summary": "This\u0020controller\u0020provides\u0020content\u0020management\u0020controller\u0020for\u0020displaying\u0020contents\u0020in\u0020host\u0020route.",
            "url": "classes/App-Controllers-Content-OrganizationProfile.html"
        },                {
            "fqsen": "\\App\\Controllers\\Content\\OrganizationProfile\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "Prepare\u0020LandingModel,\u0020ActivitiesModel,\u0020MembersModel\u0020for\u0020every\nmethod\u0020available\u0020for\u0020simplicity.",
            "url": "classes/App-Controllers-Content-OrganizationProfile.html#method___construct"
        },                {
            "fqsen": "\\App\\Controllers\\Content\\OrganizationProfile\u003A\u003Aindex\u0028\u0029",
            "name": "index",
            "summary": "Create\u0020view\u0020for\u0020index\u0020page\u0020navigation\u0020for\nchanging\u0020landing\u0020information.",
            "url": "classes/App-Controllers-Content-OrganizationProfile.html#method_index"
        },                {
            "fqsen": "\\App\\Controllers\\Content\\OrganizationProfile\u003A\u003AmainInfo\u0028\u0029",
            "name": "mainInfo",
            "summary": "Create\u0020view\u0020form\u0020for\u0020mainInfo.",
            "url": "classes/App-Controllers-Content-OrganizationProfile.html#method_mainInfo"
        },                {
            "fqsen": "\\App\\Controllers\\Content\\OrganizationProfile\u003A\u003A_updateMainInfo\u0028\u0029",
            "name": "_updateMainInfo",
            "summary": "Form\u0020validation\u0020and\u0020save\u0020data\u0020by\u0020model\u0020for\u0020mainInfo.",
            "url": "classes/App-Controllers-Content-OrganizationProfile.html#method__updateMainInfo"
        },                {
            "fqsen": "\\App\\Controllers\\Content\\OrganizationProfile\u003A\u003AourActivities\u0028\u0029",
            "name": "ourActivities",
            "summary": "Create\u0020view\u0020form\u0020for\u0020ourActivities.",
            "url": "classes/App-Controllers-Content-OrganizationProfile.html#method_ourActivities"
        },                {
            "fqsen": "\\App\\Controllers\\Content\\OrganizationProfile\u003A\u003A_updateOurActivities\u0028\u0029",
            "name": "_updateOurActivities",
            "summary": "Form\u0020validation\u0020for\u0020ourActivities.",
            "url": "classes/App-Controllers-Content-OrganizationProfile.html#method__updateOurActivities"
        },                {
            "fqsen": "\\App\\Controllers\\Content\\OrganizationProfile\u003A\u003Amembers\u0028\u0029",
            "name": "members",
            "summary": "Prepare\u0020basic\u0020view\u0020for\u0020members\u0020table\u0020before\u0020retrieve\u0020its\u0020data\u0020from\u0020datatables.",
            "url": "classes/App-Controllers-Content-OrganizationProfile.html#method_members"
        },                {
            "fqsen": "\\App\\Controllers\\Content\\OrganizationProfile\u003A\u003A_membersDatatable\u0028\u0029",
            "name": "_membersDatatable",
            "summary": "Members\u0020Datatables\u0020generator.",
            "url": "classes/App-Controllers-Content-OrganizationProfile.html#method__membersDatatable"
        },                {
            "fqsen": "\\App\\Controllers\\Content\\OrganizationProfile\u003A\u003A_delete\u0028\u0029",
            "name": "_delete",
            "summary": "Members\u0020delete\u0020ajax\u0020call.",
            "url": "classes/App-Controllers-Content-OrganizationProfile.html#method__delete"
        },                {
            "fqsen": "\\App\\Controllers\\Content\\OrganizationProfile\u003A\u003AmemberCrud\u0028\u0029",
            "name": "memberCrud",
            "summary": "Create\u0020form\u0020view\u0020for\u0020creating\u0020and\u0020updating\u0020member\u0020data.",
            "url": "classes/App-Controllers-Content-OrganizationProfile.html#method_memberCrud"
        },                {
            "fqsen": "\\App\\Controllers\\Content\\OrganizationProfile\u003A\u003A_memberCrud\u0028\u0029",
            "name": "_memberCrud",
            "summary": "Form\u0020validation\u0020and\u0020save\u0020data\u0020handler\u0020for\u0020members.",
            "url": "classes/App-Controllers-Content-OrganizationProfile.html#method__memberCrud"
        },                {
            "fqsen": "\\App\\Controllers\\Content\\OrganizationProfile\u003A\u003A\u0024lm",
            "name": "lm",
            "summary": "LandingModel\u0020initiator",
            "url": "classes/App-Controllers-Content-OrganizationProfile.html#property_lm"
        },                {
            "fqsen": "\\App\\Controllers\\Content\\OrganizationProfile\u003A\u003A\u0024am",
            "name": "am",
            "summary": "ActivitiesModel\u0020initiator",
            "url": "classes/App-Controllers-Content-OrganizationProfile.html#property_am"
        },                {
            "fqsen": "\\App\\Controllers\\Content\\OrganizationProfile\u003A\u003A\u0024mm",
            "name": "mm",
            "summary": "MembersModel\u0020initiator",
            "url": "classes/App-Controllers-Content-OrganizationProfile.html#property_mm"
        },                {
            "fqsen": "\\App\\Controllers\\Home",
            "name": "Home",
            "summary": "Class\u0020BaseController",
            "url": "classes/App-Controllers-Home.html"
        },                {
            "fqsen": "\\App\\Controllers\\Home\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/App-Controllers-Home.html#method___construct"
        },                {
            "fqsen": "\\App\\Controllers\\Home\u003A\u003Aindex\u0028\u0029",
            "name": "index",
            "summary": "",
            "url": "classes/App-Controllers-Home.html#method_index"
        },                {
            "fqsen": "\\App\\Controllers\\Home\u003A\u003Ahistory\u0028\u0029",
            "name": "history",
            "summary": "",
            "url": "classes/App-Controllers-Home.html#method_history"
        },                {
            "fqsen": "\\App\\Controllers\\Home\u003A\u003AcontactUs\u0028\u0029",
            "name": "contactUs",
            "summary": "",
            "url": "classes/App-Controllers-Home.html#method_contactUs"
        },                {
            "fqsen": "\\App\\Controllers\\Home\u003A\u003Asitemap\u0028\u0029",
            "name": "sitemap",
            "summary": "",
            "url": "classes/App-Controllers-Home.html#method_sitemap"
        },                {
            "fqsen": "\\App\\Controllers\\Home\u003A\u003A_sendMessage\u0028\u0029",
            "name": "_sendMessage",
            "summary": "",
            "url": "classes/App-Controllers-Home.html#method__sendMessage"
        },                {
            "fqsen": "\\App\\Controllers\\Home\u003A\u003A_sendNotification\u0028\u0029",
            "name": "_sendNotification",
            "summary": "",
            "url": "classes/App-Controllers-Home.html#method__sendNotification"
        },                {
            "fqsen": "\\App\\Controllers\\Home\u003A\u003A\u0024lm",
            "name": "lm",
            "summary": "",
            "url": "classes/App-Controllers-Home.html#property_lm"
        },                {
            "fqsen": "\\App\\Controllers\\Home\u003A\u003A\u0024am",
            "name": "am",
            "summary": "",
            "url": "classes/App-Controllers-Home.html#property_am"
        },                {
            "fqsen": "\\App\\Controllers\\Home\u003A\u003A\u0024mm",
            "name": "mm",
            "summary": "",
            "url": "classes/App-Controllers-Home.html#property_mm"
        },                {
            "fqsen": "\\App\\Controllers\\Home\u003A\u003A\u0024hm",
            "name": "hm",
            "summary": "",
            "url": "classes/App-Controllers-Home.html#property_hm"
        },                {
            "fqsen": "\\App\\Controllers\\Home\u003A\u003A\u0024msm",
            "name": "msm",
            "summary": "",
            "url": "classes/App-Controllers-Home.html#property_msm"
        },                {
            "fqsen": "\\App\\Controllers\\User\\Home",
            "name": "Home",
            "summary": "This\u0020controller\u0020used\u0020for\u0020dashboard\u0020and\u0020load\u0020private\u0020images\u0020\u0028logged\u0020in\u0020only\u0029.",
            "url": "classes/App-Controllers-User-Home.html"
        },                {
            "fqsen": "\\App\\Controllers\\User\\Home\u003A\u003Aindex\u0028\u0029",
            "name": "index",
            "summary": "Prepare\u0020dashboard\u0020view",
            "url": "classes/App-Controllers-User-Home.html#method_index"
        },                {
            "fqsen": "\\App\\Controllers\\User\\Home\u003A\u003AloadImage\u0028\u0029",
            "name": "loadImage",
            "summary": "Provides\u0020function\u0020call\u0020for\u0020private\u0020images,\u0020called\u0020from\u0020host\/gambar\u002Dprivate\u003Fq\u003D...\u0020url",
            "url": "classes/App-Controllers-User-Home.html#method_loadImage"
        },                {
            "fqsen": "\\App\\Controllers\\User\\Profile",
            "name": "Profile",
            "summary": "This\u0020controller\u0020purpose\u0020is\u0020to\u0020change\u0020user\u0020account\u0020details.",
            "url": "classes/App-Controllers-User-Profile.html"
        },                {
            "fqsen": "\\App\\Controllers\\User\\Profile\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "Construct\u0020UsersModel.",
            "url": "classes/App-Controllers-User-Profile.html#method___construct"
        },                {
            "fqsen": "\\App\\Controllers\\User\\Profile\u003A\u003Aindex\u0028\u0029",
            "name": "index",
            "summary": "This\u0020method\u0020is\u0020to\u0020show\u0020form\u0020view\u0020of\u0020profile\/account\u0020settings.",
            "url": "classes/App-Controllers-User-Profile.html#method_index"
        },                {
            "fqsen": "\\App\\Controllers\\User\\Profile\u003A\u003A_updateProfile\u0028\u0029",
            "name": "_updateProfile",
            "summary": "Validate\u0020and\u0020submit\u0020form\u0020to\u0020database.",
            "url": "classes/App-Controllers-User-Profile.html#method__updateProfile"
        },                {
            "fqsen": "\\App\\Controllers\\User\\Profile\u003A\u003A_verifyEmail\u0028\u0029",
            "name": "_verifyEmail",
            "summary": "Send\u0020email\u0020method\u0020to\u0020new\u0020email\u0020posted\u0020on\u0020the\u0020form.",
            "url": "classes/App-Controllers-User-Profile.html#method__verifyEmail"
        },                {
            "fqsen": "\\App\\Controllers\\User\\Profile\u003A\u003A\u0024um",
            "name": "um",
            "summary": "",
            "url": "classes/App-Controllers-User-Profile.html#property_um"
        },                {
            "fqsen": "\\checkAuth\u0028\u0029",
            "name": "checkAuth",
            "summary": "",
            "url": "namespaces/default.html#function_checkAuth"
        },                {
            "fqsen": "\\isExcluded\u0028\u0029",
            "name": "isExcluded",
            "summary": "",
            "url": "namespaces/default.html#function_isExcluded"
        },                {
            "fqsen": "\\filterOutput\u0028\u0029",
            "name": "filterOutput",
            "summary": "",
            "url": "namespaces/default.html#function_filterOutput"
        },                {
            "fqsen": "\\htmlEscape\u0028\u0029",
            "name": "htmlEscape",
            "summary": "Returns\u0020HTML\u0020escaped\u0020variable.",
            "url": "namespaces/default.html#function_htmlEscape"
        },                {
            "fqsen": "\\encode\u0028\u0029",
            "name": "encode",
            "summary": "",
            "url": "namespaces/default.html#function_encode"
        },                {
            "fqsen": "\\decode\u0028\u0029",
            "name": "decode",
            "summary": "",
            "url": "namespaces/default.html#function_decode"
        },                {
            "fqsen": "\\show404\u0028\u0029",
            "name": "show404",
            "summary": "",
            "url": "namespaces/default.html#function_show404"
        },                {
            "fqsen": "\\getCaptchaSitekey\u0028\u0029",
            "name": "getCaptchaSitekey",
            "summary": "",
            "url": "namespaces/default.html#function_getCaptchaSitekey"
        },                {
            "fqsen": "\\kartaPasswordHash\u0028\u0029",
            "name": "kartaPasswordHash",
            "summary": "",
            "url": "namespaces/default.html#function_kartaPasswordHash"
        },                {
            "fqsen": "\\kartaPasswordVerify\u0028\u0029",
            "name": "kartaPasswordVerify",
            "summary": "",
            "url": "namespaces/default.html#function_kartaPasswordVerify"
        },                {
            "fqsen": "\\getMethod\u0028\u0029",
            "name": "getMethod",
            "summary": "",
            "url": "namespaces/default.html#function_getMethod"
        },                {
            "fqsen": "\\acceptFrom\u0028\u0029",
            "name": "acceptFrom",
            "summary": "",
            "url": "namespaces/default.html#function_acceptFrom"
        },                {
            "fqsen": "\\removeProtocol\u0028\u0029",
            "name": "removeProtocol",
            "summary": "",
            "url": "namespaces/default.html#function_removeProtocol"
        },                {
            "fqsen": "\\addProtocol\u0028\u0029",
            "name": "addProtocol",
            "summary": "",
            "url": "namespaces/default.html#function_addProtocol"
        },                {
            "fqsen": "\\objectify\u0028\u0029",
            "name": "objectify",
            "summary": "",
            "url": "namespaces/default.html#function_objectify"
        },                {
            "fqsen": "\\setFlash\u0028\u0029",
            "name": "setFlash",
            "summary": "",
            "url": "namespaces/default.html#function_setFlash"
        },                {
            "fqsen": "\\getFlash\u0028\u0029",
            "name": "getFlash",
            "summary": "",
            "url": "namespaces/default.html#function_getFlash"
        },                {
            "fqsen": "\\parseMission\u0028\u0029",
            "name": "parseMission",
            "summary": "",
            "url": "namespaces/default.html#function_parseMission"
        },                {
            "fqsen": "\\setInvalid\u0028\u0029",
            "name": "setInvalid",
            "summary": "",
            "url": "namespaces/default.html#function_setInvalid"
        },                {
            "fqsen": "\\showInvalidFeedback\u0028\u0029",
            "name": "showInvalidFeedback",
            "summary": "",
            "url": "namespaces/default.html#function_showInvalidFeedback"
        },                {
            "fqsen": "\\countTable\u0028\u0029",
            "name": "countTable",
            "summary": "",
            "url": "namespaces/default.html#function_countTable"
        },                {
            "fqsen": "\\isSamePage\u0028\u0029",
            "name": "isSamePage",
            "summary": "",
            "url": "namespaces/default.html#function_isSamePage"
        },                {
            "fqsen": "\\getSidebarMenu\u0028\u0029",
            "name": "getSidebarMenu",
            "summary": "",
            "url": "namespaces/default.html#function_getSidebarMenu"
        },                {
            "fqsen": "\\isSameController\u0028\u0029",
            "name": "isSameController",
            "summary": "",
            "url": "namespaces/default.html#function_isSameController"
        },                {
            "fqsen": "\\getCallToAction\u0028\u0029",
            "name": "getCallToAction",
            "summary": "",
            "url": "namespaces/default.html#function_getCallToAction"
        },                {
            "fqsen": "\\getUserName\u0028\u0029",
            "name": "getUserName",
            "summary": "",
            "url": "namespaces/default.html#function_getUserName"
        },                {
            "fqsen": "\\getMissions\u0028\u0029",
            "name": "getMissions",
            "summary": "",
            "url": "namespaces/default.html#function_getMissions"
        },                {
            "fqsen": "\\App\\Libraries\\DatabaseManager",
            "name": "DatabaseManager",
            "summary": "",
            "url": "classes/App-Libraries-DatabaseManager.html"
        },                {
            "fqsen": "\\App\\Libraries\\DatabaseManager\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/App-Libraries-DatabaseManager.html#method___construct"
        },                {
            "fqsen": "\\App\\Libraries\\DatabaseManager\u003A\u003AfilterDatatables\u0028\u0029",
            "name": "filterDatatables",
            "summary": "",
            "url": "classes/App-Libraries-DatabaseManager.html#method_filterDatatables"
        },                {
            "fqsen": "\\App\\Libraries\\DatabaseManager\u003A\u003AcountAll\u0028\u0029",
            "name": "countAll",
            "summary": "",
            "url": "classes/App-Libraries-DatabaseManager.html#method_countAll"
        },                {
            "fqsen": "\\App\\Libraries\\DatabaseManager\u003A\u003Aread\u0028\u0029",
            "name": "read",
            "summary": "Read\u0020function",
            "url": "classes/App-Libraries-DatabaseManager.html#method_read"
        },                {
            "fqsen": "\\App\\Libraries\\DatabaseManager\u003A\u003AmakeGroup\u0028\u0029",
            "name": "makeGroup",
            "summary": "",
            "url": "classes/App-Libraries-DatabaseManager.html#method_makeGroup"
        },                {
            "fqsen": "\\App\\Libraries\\DatabaseManager\u003A\u003Atranslate\u0028\u0029",
            "name": "translate",
            "summary": "",
            "url": "classes/App-Libraries-DatabaseManager.html#method_translate"
        },                {
            "fqsen": "\\App\\Libraries\\DatabaseManager\u003A\u003A\u0024db",
            "name": "db",
            "summary": "",
            "url": "classes/App-Libraries-DatabaseManager.html#property_db"
        },                {
            "fqsen": "\\App\\Libraries\\DatabaseManager\u003A\u003A\u0024builder",
            "name": "builder",
            "summary": "",
            "url": "classes/App-Libraries-DatabaseManager.html#property_builder"
        },                {
            "fqsen": "\\App\\Libraries\\ImageUploader",
            "name": "ImageUploader",
            "summary": "",
            "url": "classes/App-Libraries-ImageUploader.html"
        },                {
            "fqsen": "\\App\\Libraries\\ImageUploader\u003A\u003Aupload\u0028\u0029",
            "name": "upload",
            "summary": "",
            "url": "classes/App-Libraries-ImageUploader.html#method_upload"
        },                {
            "fqsen": "\\App\\Libraries\\ImageUploader\u003A\u003AconvertToWebp\u0028\u0029",
            "name": "convertToWebp",
            "summary": "Convert\u0020to\u0020webp\u0020and\u0020compress",
            "url": "classes/App-Libraries-ImageUploader.html#method_convertToWebp"
        },                {
            "fqsen": "\\App\\Libraries\\Model",
            "name": "Model",
            "summary": "",
            "url": "classes/App-Libraries-Model.html"
        },                {
            "fqsen": "\\App\\Libraries\\Model\u003A\u003AgetValidationRules\u0028\u0029",
            "name": "getValidationRules",
            "summary": "Returns\u0020the\u0020model\u0027s\u0020defined\u0020validation\u0020rules\u0020so\u0020that\u0020they\ncan\u0020be\u0020used\u0020elsewhere,\u0020if\u0020needed.",
            "url": "classes/App-Libraries-Model.html#method_getValidationRules"
        },                {
            "fqsen": "\\App\\Libraries\\Model\u003A\u003Afind\u0028\u0029",
            "name": "find",
            "summary": "Fetches\u0020the\u0020row\u0020of\u0020database",
            "url": "classes/App-Libraries-Model.html#method_find"
        },                {
            "fqsen": "\\App\\Libraries\\Model\u003A\u003AsetModifiedBy\u0028\u0029",
            "name": "setModifiedBy",
            "summary": "",
            "url": "classes/App-Libraries-Model.html#method_setModifiedBy"
        },                {
            "fqsen": "\\App\\Libraries\\Model\u003A\u003AsetCreatedBy\u0028\u0029",
            "name": "setCreatedBy",
            "summary": "",
            "url": "classes/App-Libraries-Model.html#method_setCreatedBy"
        },                {
            "fqsen": "\\App\\Libraries\\Model\u003A\u003AsetDeletedBy\u0028\u0029",
            "name": "setDeletedBy",
            "summary": "",
            "url": "classes/App-Libraries-Model.html#method_setDeletedBy"
        },                {
            "fqsen": "\\App\\Libraries\\RedirectResponse",
            "name": "RedirectResponse",
            "summary": "",
            "url": "classes/App-Libraries-RedirectResponse.html"
        },                {
            "fqsen": "\\App\\Libraries\\RedirectResponse\u003A\u003Ato\u0028\u0029",
            "name": "to",
            "summary": "Sets\u0020the\u0020URI\u0020to\u0020redirect\u0020to\u0020and,\u0020optionally,\u0020the\u0020HTTP\u0020status\u0020code\u0020to\u0020use.",
            "url": "classes/App-Libraries-RedirectResponse.html#method_to"
        },                {
            "fqsen": "\\App\\Models\\ActivitiesModel",
            "name": "ActivitiesModel",
            "summary": "",
            "url": "classes/App-Models-ActivitiesModel.html"
        },                {
            "fqsen": "\\App\\Models\\ActivitiesModel\u003A\u003A\u0024table",
            "name": "table",
            "summary": "",
            "url": "classes/App-Models-ActivitiesModel.html#property_table"
        },                {
            "fqsen": "\\App\\Models\\ActivitiesModel\u003A\u003A\u0024primaryKey",
            "name": "primaryKey",
            "summary": "",
            "url": "classes/App-Models-ActivitiesModel.html#property_primaryKey"
        },                {
            "fqsen": "\\App\\Models\\ActivitiesModel\u003A\u003A\u0024useTimestamps",
            "name": "useTimestamps",
            "summary": "",
            "url": "classes/App-Models-ActivitiesModel.html#property_useTimestamps"
        },                {
            "fqsen": "\\App\\Models\\ActivitiesModel\u003A\u003A\u0024allowedFields",
            "name": "allowedFields",
            "summary": "",
            "url": "classes/App-Models-ActivitiesModel.html#property_allowedFields"
        },                {
            "fqsen": "\\App\\Models\\ActivitiesModel\u003A\u003A\u0024returnType",
            "name": "returnType",
            "summary": "",
            "url": "classes/App-Models-ActivitiesModel.html#property_returnType"
        },                {
            "fqsen": "\\App\\Models\\ActivitiesModel\u003A\u003A\u0024beforeUpdate",
            "name": "beforeUpdate",
            "summary": "",
            "url": "classes/App-Models-ActivitiesModel.html#property_beforeUpdate"
        },                {
            "fqsen": "\\App\\Models\\ActivitiesModel\u003A\u003A\u0024validationRules",
            "name": "validationRules",
            "summary": "",
            "url": "classes/App-Models-ActivitiesModel.html#property_validationRules"
        },                {
            "fqsen": "\\App\\Models\\HistoryModel",
            "name": "HistoryModel",
            "summary": "",
            "url": "classes/App-Models-HistoryModel.html"
        },                {
            "fqsen": "\\App\\Models\\HistoryModel\u003A\u003A\u0024table",
            "name": "table",
            "summary": "",
            "url": "classes/App-Models-HistoryModel.html#property_table"
        },                {
            "fqsen": "\\App\\Models\\HistoryModel\u003A\u003A\u0024primaryKey",
            "name": "primaryKey",
            "summary": "",
            "url": "classes/App-Models-HistoryModel.html#property_primaryKey"
        },                {
            "fqsen": "\\App\\Models\\HistoryModel\u003A\u003A\u0024useTimestamps",
            "name": "useTimestamps",
            "summary": "",
            "url": "classes/App-Models-HistoryModel.html#property_useTimestamps"
        },                {
            "fqsen": "\\App\\Models\\HistoryModel\u003A\u003A\u0024allowedFields",
            "name": "allowedFields",
            "summary": "",
            "url": "classes/App-Models-HistoryModel.html#property_allowedFields"
        },                {
            "fqsen": "\\App\\Models\\HistoryModel\u003A\u003A\u0024afterUpdate",
            "name": "afterUpdate",
            "summary": "",
            "url": "classes/App-Models-HistoryModel.html#property_afterUpdate"
        },                {
            "fqsen": "\\App\\Models\\HistoryModel\u003A\u003A\u0024validationRules",
            "name": "validationRules",
            "summary": "",
            "url": "classes/App-Models-HistoryModel.html#property_validationRules"
        },                {
            "fqsen": "\\App\\Models\\HistoryModel\u003A\u003A\u0024returnType",
            "name": "returnType",
            "summary": "",
            "url": "classes/App-Models-HistoryModel.html#property_returnType"
        },                {
            "fqsen": "\\App\\Models\\LandingModel",
            "name": "LandingModel",
            "summary": "",
            "url": "classes/App-Models-LandingModel.html"
        },                {
            "fqsen": "\\App\\Models\\LandingModel\u003A\u003AgetCallToAction\u0028\u0029",
            "name": "getCallToAction",
            "summary": "",
            "url": "classes/App-Models-LandingModel.html#method_getCallToAction"
        },                {
            "fqsen": "\\App\\Models\\LandingModel\u003A\u003A\u0024table",
            "name": "table",
            "summary": "",
            "url": "classes/App-Models-LandingModel.html#property_table"
        },                {
            "fqsen": "\\App\\Models\\LandingModel\u003A\u003A\u0024primaryKey",
            "name": "primaryKey",
            "summary": "",
            "url": "classes/App-Models-LandingModel.html#property_primaryKey"
        },                {
            "fqsen": "\\App\\Models\\LandingModel\u003A\u003A\u0024useTimestamps",
            "name": "useTimestamps",
            "summary": "",
            "url": "classes/App-Models-LandingModel.html#property_useTimestamps"
        },                {
            "fqsen": "\\App\\Models\\LandingModel\u003A\u003A\u0024allowedFields",
            "name": "allowedFields",
            "summary": "",
            "url": "classes/App-Models-LandingModel.html#property_allowedFields"
        },                {
            "fqsen": "\\App\\Models\\LandingModel\u003A\u003A\u0024returnType",
            "name": "returnType",
            "summary": "",
            "url": "classes/App-Models-LandingModel.html#property_returnType"
        },                {
            "fqsen": "\\App\\Models\\LandingModel\u003A\u003A\u0024beforeUpdate",
            "name": "beforeUpdate",
            "summary": "",
            "url": "classes/App-Models-LandingModel.html#property_beforeUpdate"
        },                {
            "fqsen": "\\App\\Models\\LandingModel\u003A\u003A\u0024validationRules",
            "name": "validationRules",
            "summary": "",
            "url": "classes/App-Models-LandingModel.html#property_validationRules"
        },                {
            "fqsen": "\\App\\Models\\MembersModel",
            "name": "MembersModel",
            "summary": "",
            "url": "classes/App-Models-MembersModel.html"
        },                {
            "fqsen": "\\App\\Models\\MembersModel\u003A\u003AgetMembers\u0028\u0029",
            "name": "getMembers",
            "summary": "",
            "url": "classes/App-Models-MembersModel.html#method_getMembers"
        },                {
            "fqsen": "\\App\\Models\\MembersModel\u003A\u003AgetDatatable\u0028\u0029",
            "name": "getDatatable",
            "summary": "",
            "url": "classes/App-Models-MembersModel.html#method_getDatatable"
        },                {
            "fqsen": "\\App\\Models\\MembersModel\u003A\u003A\u0024table",
            "name": "table",
            "summary": "",
            "url": "classes/App-Models-MembersModel.html#property_table"
        },                {
            "fqsen": "\\App\\Models\\MembersModel\u003A\u003A\u0024primaryKey",
            "name": "primaryKey",
            "summary": "",
            "url": "classes/App-Models-MembersModel.html#property_primaryKey"
        },                {
            "fqsen": "\\App\\Models\\MembersModel\u003A\u003A\u0024useTimestamps",
            "name": "useTimestamps",
            "summary": "",
            "url": "classes/App-Models-MembersModel.html#property_useTimestamps"
        },                {
            "fqsen": "\\App\\Models\\MembersModel\u003A\u003A\u0024allowedFields",
            "name": "allowedFields",
            "summary": "",
            "url": "classes/App-Models-MembersModel.html#property_allowedFields"
        },                {
            "fqsen": "\\App\\Models\\MembersModel\u003A\u003A\u0024returnType",
            "name": "returnType",
            "summary": "",
            "url": "classes/App-Models-MembersModel.html#property_returnType"
        },                {
            "fqsen": "\\App\\Models\\MembersModel\u003A\u003A\u0024useSoftDeletes",
            "name": "useSoftDeletes",
            "summary": "",
            "url": "classes/App-Models-MembersModel.html#property_useSoftDeletes"
        },                {
            "fqsen": "\\App\\Models\\MembersModel\u003A\u003A\u0024beforeInsert",
            "name": "beforeInsert",
            "summary": "",
            "url": "classes/App-Models-MembersModel.html#property_beforeInsert"
        },                {
            "fqsen": "\\App\\Models\\MembersModel\u003A\u003A\u0024beforeUpdate",
            "name": "beforeUpdate",
            "summary": "",
            "url": "classes/App-Models-MembersModel.html#property_beforeUpdate"
        },                {
            "fqsen": "\\App\\Models\\MembersModel\u003A\u003A\u0024afterDelete",
            "name": "afterDelete",
            "summary": "",
            "url": "classes/App-Models-MembersModel.html#property_afterDelete"
        },                {
            "fqsen": "\\App\\Models\\MembersModel\u003A\u003A\u0024validationRules",
            "name": "validationRules",
            "summary": "",
            "url": "classes/App-Models-MembersModel.html#property_validationRules"
        },                {
            "fqsen": "\\App\\Models\\MenuModel",
            "name": "MenuModel",
            "summary": "",
            "url": "classes/App-Models-MenuModel.html"
        },                {
            "fqsen": "\\App\\Models\\MenuModel\u003A\u003AgetMenuId\u0028\u0029",
            "name": "getMenuId",
            "summary": "",
            "url": "classes/App-Models-MenuModel.html#method_getMenuId"
        },                {
            "fqsen": "\\App\\Models\\MenuModel\u003A\u003A\u0024table",
            "name": "table",
            "summary": "",
            "url": "classes/App-Models-MenuModel.html#property_table"
        },                {
            "fqsen": "\\App\\Models\\MenuModel\u003A\u003A\u0024primaryKey",
            "name": "primaryKey",
            "summary": "",
            "url": "classes/App-Models-MenuModel.html#property_primaryKey"
        },                {
            "fqsen": "\\App\\Models\\MenuModel\u003A\u003A\u0024allowedFields",
            "name": "allowedFields",
            "summary": "",
            "url": "classes/App-Models-MenuModel.html#property_allowedFields"
        },                {
            "fqsen": "\\App\\Models\\MenuModel\u003A\u003A\u0024returnType",
            "name": "returnType",
            "summary": "",
            "url": "classes/App-Models-MenuModel.html#property_returnType"
        },                {
            "fqsen": "\\App\\Models\\RoleAccessModel",
            "name": "RoleAccessModel",
            "summary": "",
            "url": "classes/App-Models-RoleAccessModel.html"
        },                {
            "fqsen": "\\App\\Models\\RoleAccessModel\u003A\u003AgetRoleAccessId\u0028\u0029",
            "name": "getRoleAccessId",
            "summary": "",
            "url": "classes/App-Models-RoleAccessModel.html#method_getRoleAccessId"
        },                {
            "fqsen": "\\App\\Models\\RoleAccessModel\u003A\u003AgetPageByRole\u0028\u0029",
            "name": "getPageByRole",
            "summary": "",
            "url": "classes/App-Models-RoleAccessModel.html#method_getPageByRole"
        },                {
            "fqsen": "\\App\\Models\\RoleAccessModel\u003A\u003A\u0024table",
            "name": "table",
            "summary": "",
            "url": "classes/App-Models-RoleAccessModel.html#property_table"
        },                {
            "fqsen": "\\App\\Models\\RoleAccessModel\u003A\u003A\u0024primaryKey",
            "name": "primaryKey",
            "summary": "",
            "url": "classes/App-Models-RoleAccessModel.html#property_primaryKey"
        },                {
            "fqsen": "\\App\\Models\\RoleAccessModel\u003A\u003A\u0024allowedFields",
            "name": "allowedFields",
            "summary": "",
            "url": "classes/App-Models-RoleAccessModel.html#property_allowedFields"
        },                {
            "fqsen": "\\App\\Models\\RoleAccessModel\u003A\u003A\u0024returnType",
            "name": "returnType",
            "summary": "",
            "url": "classes/App-Models-RoleAccessModel.html#property_returnType"
        },                {
            "fqsen": "\\App\\Models\\UsersModel",
            "name": "UsersModel",
            "summary": "",
            "url": "classes/App-Models-UsersModel.html"
        },                {
            "fqsen": "\\App\\Models\\UsersModel\u003A\u003AgetFromEmail\u0028\u0029",
            "name": "getFromEmail",
            "summary": "",
            "url": "classes/App-Models-UsersModel.html#method_getFromEmail"
        },                {
            "fqsen": "\\App\\Models\\UsersModel\u003A\u003A\u0024table",
            "name": "table",
            "summary": "",
            "url": "classes/App-Models-UsersModel.html#property_table"
        },                {
            "fqsen": "\\App\\Models\\UsersModel\u003A\u003A\u0024primaryKey",
            "name": "primaryKey",
            "summary": "",
            "url": "classes/App-Models-UsersModel.html#property_primaryKey"
        },                {
            "fqsen": "\\App\\Models\\UsersModel\u003A\u003A\u0024useTimestamps",
            "name": "useTimestamps",
            "summary": "",
            "url": "classes/App-Models-UsersModel.html#property_useTimestamps"
        },                {
            "fqsen": "\\App\\Models\\UsersModel\u003A\u003A\u0024allowedFields",
            "name": "allowedFields",
            "summary": "",
            "url": "classes/App-Models-UsersModel.html#property_allowedFields"
        },                {
            "fqsen": "\\App\\Models\\UsersModel\u003A\u003A\u0024returnType",
            "name": "returnType",
            "summary": "",
            "url": "classes/App-Models-UsersModel.html#property_returnType"
        },                {
            "fqsen": "\\App\\Models\\UsersModel\u003A\u003A\u0024validationRules",
            "name": "validationRules",
            "summary": "",
            "url": "classes/App-Models-UsersModel.html#property_validationRules"
        },                {
            "fqsen": "\\App\\Models\\CommunitiesModel",
            "name": "CommunitiesModel",
            "summary": "",
            "url": "classes/App-Models-CommunitiesModel.html"
        },                {
            "fqsen": "\\App\\Models\\CommunitiesModel\u003A\u003AgetPMKSDatatable\u0028\u0029",
            "name": "getPMKSDatatable",
            "summary": "",
            "url": "classes/App-Models-CommunitiesModel.html#method_getPMKSDatatable"
        },                {
            "fqsen": "\\App\\Models\\CommunitiesModel\u003A\u003AgetPSKSDatatable\u0028\u0029",
            "name": "getPSKSDatatable",
            "summary": "",
            "url": "classes/App-Models-CommunitiesModel.html#method_getPSKSDatatable"
        },                {
            "fqsen": "\\App\\Models\\CommunitiesModel\u003A\u003A\u0024table",
            "name": "table",
            "summary": "",
            "url": "classes/App-Models-CommunitiesModel.html#property_table"
        },                {
            "fqsen": "\\App\\Models\\CommunitiesModel\u003A\u003A\u0024primaryKey",
            "name": "primaryKey",
            "summary": "",
            "url": "classes/App-Models-CommunitiesModel.html#property_primaryKey"
        },                {
            "fqsen": "\\App\\Models\\CommunitiesModel\u003A\u003A\u0024useTimestamps",
            "name": "useTimestamps",
            "summary": "",
            "url": "classes/App-Models-CommunitiesModel.html#property_useTimestamps"
        },                {
            "fqsen": "\\App\\Models\\CommunitiesModel\u003A\u003A\u0024allowedFields",
            "name": "allowedFields",
            "summary": "",
            "url": "classes/App-Models-CommunitiesModel.html#property_allowedFields"
        },                {
            "fqsen": "\\App\\Models\\CommunitiesModel\u003A\u003A\u0024returnType",
            "name": "returnType",
            "summary": "",
            "url": "classes/App-Models-CommunitiesModel.html#property_returnType"
        },                {
            "fqsen": "\\App\\Models\\CommunitiesModel\u003A\u003A\u0024useSoftDeletes",
            "name": "useSoftDeletes",
            "summary": "",
            "url": "classes/App-Models-CommunitiesModel.html#property_useSoftDeletes"
        },                {
            "fqsen": "\\App\\Models\\CommunitiesModel\u003A\u003A\u0024beforeInsert",
            "name": "beforeInsert",
            "summary": "",
            "url": "classes/App-Models-CommunitiesModel.html#property_beforeInsert"
        },                {
            "fqsen": "\\App\\Models\\CommunitiesModel\u003A\u003A\u0024beforeUpdate",
            "name": "beforeUpdate",
            "summary": "",
            "url": "classes/App-Models-CommunitiesModel.html#property_beforeUpdate"
        },                {
            "fqsen": "\\App\\Models\\CommunitiesModel\u003A\u003A\u0024afterDelete",
            "name": "afterDelete",
            "summary": "",
            "url": "classes/App-Models-CommunitiesModel.html#property_afterDelete"
        },                {
            "fqsen": "\\App\\Models\\CommunitiesModel\u003A\u003A\u0024validationRules",
            "name": "validationRules",
            "summary": "",
            "url": "classes/App-Models-CommunitiesModel.html#property_validationRules"
        },                {
            "fqsen": "\\App\\Controllers\\Data\\Messages",
            "name": "Messages",
            "summary": "This\u0020controller\u0020shows\u0020Messages\u0020data.",
            "url": "classes/App-Controllers-Data-Messages.html"
        },                {
            "fqsen": "\\App\\Controllers\\Data\\Messages\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "Prepare\u0020MessagesModel.",
            "url": "classes/App-Controllers-Data-Messages.html#method___construct"
        },                {
            "fqsen": "\\App\\Controllers\\Data\\Messages\u003A\u003Aindex\u0028\u0029",
            "name": "index",
            "summary": "",
            "url": "classes/App-Controllers-Data-Messages.html#method_index"
        },                {
            "fqsen": "\\App\\Controllers\\Data\\Messages\u003A\u003A_datatable\u0028\u0029",
            "name": "_datatable",
            "summary": "",
            "url": "classes/App-Controllers-Data-Messages.html#method__datatable"
        },                {
            "fqsen": "\\App\\Controllers\\Data\\Messages\u003A\u003A_updateStatus\u0028\u0029",
            "name": "_updateStatus",
            "summary": "",
            "url": "classes/App-Controllers-Data-Messages.html#method__updateStatus"
        },                {
            "fqsen": "\\App\\Controllers\\Data\\Messages\u003A\u003A_delete\u0028\u0029",
            "name": "_delete",
            "summary": "",
            "url": "classes/App-Controllers-Data-Messages.html#method__delete"
        },                {
            "fqsen": "\\App\\Controllers\\Data\\Messages\u003A\u003A\u0024msm",
            "name": "msm",
            "summary": "",
            "url": "classes/App-Controllers-Data-Messages.html#property_msm"
        },                {
            "fqsen": "\\App\\Controllers\\Data\\Pmks",
            "name": "Pmks",
            "summary": "This\u0020controller\u0020shows\u0020PMKS\u0020data.",
            "url": "classes/App-Controllers-Data-Pmks.html"
        },                {
            "fqsen": "\\App\\Controllers\\Data\\Pmks\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "Constructor\u0020provided\u0020to\u0020prepare\u0020every\u0020model.",
            "url": "classes/App-Controllers-Data-Pmks.html#method___construct"
        },                {
            "fqsen": "\\App\\Controllers\\Data\\Pmks\u003A\u003Aindex\u0028\u0029",
            "name": "index",
            "summary": "",
            "url": "classes/App-Controllers-Data-Pmks.html#method_index"
        },                {
            "fqsen": "\\App\\Controllers\\Data\\Pmks\u003A\u003A_datatable\u0028\u0029",
            "name": "_datatable",
            "summary": "",
            "url": "classes/App-Controllers-Data-Pmks.html#method__datatable"
        },                {
            "fqsen": "\\App\\Controllers\\Data\\Pmks\u003A\u003A_updateStatus\u0028\u0029",
            "name": "_updateStatus",
            "summary": "",
            "url": "classes/App-Controllers-Data-Pmks.html#method__updateStatus"
        },                {
            "fqsen": "\\App\\Controllers\\Data\\Pmks\u003A\u003A_delete\u0028\u0029",
            "name": "_delete",
            "summary": "",
            "url": "classes/App-Controllers-Data-Pmks.html#method__delete"
        },                {
            "fqsen": "\\App\\Controllers\\Data\\Pmks\u003A\u003Acrud\u0028\u0029",
            "name": "crud",
            "summary": "",
            "url": "classes/App-Controllers-Data-Pmks.html#method_crud"
        },                {
            "fqsen": "\\App\\Controllers\\Data\\Pmks\u003A\u003AspreadsheetCrud\u0028\u0029",
            "name": "spreadsheetCrud",
            "summary": "",
            "url": "classes/App-Controllers-Data-Pmks.html#method_spreadsheetCrud"
        },                {
            "fqsen": "\\App\\Controllers\\Data\\Pmks\u003A\u003A_crud\u0028\u0029",
            "name": "_crud",
            "summary": "",
            "url": "classes/App-Controllers-Data-Pmks.html#method__crud"
        },                {
            "fqsen": "\\App\\Controllers\\Data\\Pmks\u003A\u003AgetImages\u0028\u0029",
            "name": "getImages",
            "summary": "",
            "url": "classes/App-Controllers-Data-Pmks.html#method_getImages"
        },                {
            "fqsen": "\\App\\Controllers\\Data\\Pmks\u003A\u003A\u0024cm",
            "name": "cm",
            "summary": "",
            "url": "classes/App-Controllers-Data-Pmks.html#property_cm"
        },                {
            "fqsen": "\\App\\Controllers\\Data\\Pmks\u003A\u003A\u0024pim",
            "name": "pim",
            "summary": "",
            "url": "classes/App-Controllers-Data-Pmks.html#property_pim"
        },                {
            "fqsen": "\\App\\Controllers\\Data\\Pmks\u003A\u003A\u0024pm",
            "name": "pm",
            "summary": "",
            "url": "classes/App-Controllers-Data-Pmks.html#property_pm"
        },                {
            "fqsen": "\\App\\Controllers\\Data\\Psks",
            "name": "Psks",
            "summary": "This\u0020controller\u0020shows\u0020PSKS\u0020data.",
            "url": "classes/App-Controllers-Data-Psks.html"
        },                {
            "fqsen": "\\App\\Controllers\\Data\\Psks\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "Constructor\u0020provided\u0020to\u0020prepare\u0020every\u0020model.",
            "url": "classes/App-Controllers-Data-Psks.html#method___construct"
        },                {
            "fqsen": "\\App\\Controllers\\Data\\Psks\u003A\u003Aindex\u0028\u0029",
            "name": "index",
            "summary": "",
            "url": "classes/App-Controllers-Data-Psks.html#method_index"
        },                {
            "fqsen": "\\App\\Controllers\\Data\\Psks\u003A\u003A_datatable\u0028\u0029",
            "name": "_datatable",
            "summary": "",
            "url": "classes/App-Controllers-Data-Psks.html#method__datatable"
        },                {
            "fqsen": "\\App\\Controllers\\Data\\Psks\u003A\u003A_updateStatus\u0028\u0029",
            "name": "_updateStatus",
            "summary": "",
            "url": "classes/App-Controllers-Data-Psks.html#method__updateStatus"
        },                {
            "fqsen": "\\App\\Controllers\\Data\\Psks\u003A\u003A_delete\u0028\u0029",
            "name": "_delete",
            "summary": "",
            "url": "classes/App-Controllers-Data-Psks.html#method__delete"
        },                {
            "fqsen": "\\App\\Controllers\\Data\\Psks\u003A\u003Acrud\u0028\u0029",
            "name": "crud",
            "summary": "",
            "url": "classes/App-Controllers-Data-Psks.html#method_crud"
        },                {
            "fqsen": "\\App\\Controllers\\Data\\Psks\u003A\u003AspreadsheetCrud\u0028\u0029",
            "name": "spreadsheetCrud",
            "summary": "",
            "url": "classes/App-Controllers-Data-Psks.html#method_spreadsheetCrud"
        },                {
            "fqsen": "\\App\\Controllers\\Data\\Psks\u003A\u003A_crud\u0028\u0029",
            "name": "_crud",
            "summary": "",
            "url": "classes/App-Controllers-Data-Psks.html#method__crud"
        },                {
            "fqsen": "\\App\\Controllers\\Data\\Psks\u003A\u003AgetImages\u0028\u0029",
            "name": "getImages",
            "summary": "",
            "url": "classes/App-Controllers-Data-Psks.html#method_getImages"
        },                {
            "fqsen": "\\App\\Controllers\\Data\\Psks\u003A\u003A\u0024cm",
            "name": "cm",
            "summary": "",
            "url": "classes/App-Controllers-Data-Psks.html#property_cm"
        },                {
            "fqsen": "\\App\\Controllers\\Data\\Psks\u003A\u003A\u0024pim",
            "name": "pim",
            "summary": "",
            "url": "classes/App-Controllers-Data-Psks.html#property_pim"
        },                {
            "fqsen": "\\App\\Controllers\\Data\\Psks\u003A\u003A\u0024pm",
            "name": "pm",
            "summary": "",
            "url": "classes/App-Controllers-Data-Psks.html#property_pm"
        },                {
            "fqsen": "\\App\\Models\\MessagesModel",
            "name": "MessagesModel",
            "summary": "",
            "url": "classes/App-Models-MessagesModel.html"
        },                {
            "fqsen": "\\App\\Models\\MessagesModel\u003A\u003AgetDatatable\u0028\u0029",
            "name": "getDatatable",
            "summary": "",
            "url": "classes/App-Models-MessagesModel.html#method_getDatatable"
        },                {
            "fqsen": "\\App\\Models\\MessagesModel\u003A\u003A\u0024table",
            "name": "table",
            "summary": "",
            "url": "classes/App-Models-MessagesModel.html#property_table"
        },                {
            "fqsen": "\\App\\Models\\MessagesModel\u003A\u003A\u0024primaryKey",
            "name": "primaryKey",
            "summary": "",
            "url": "classes/App-Models-MessagesModel.html#property_primaryKey"
        },                {
            "fqsen": "\\App\\Models\\MessagesModel\u003A\u003A\u0024useTimestamps",
            "name": "useTimestamps",
            "summary": "",
            "url": "classes/App-Models-MessagesModel.html#property_useTimestamps"
        },                {
            "fqsen": "\\App\\Models\\MessagesModel\u003A\u003A\u0024allowedFields",
            "name": "allowedFields",
            "summary": "",
            "url": "classes/App-Models-MessagesModel.html#property_allowedFields"
        },                {
            "fqsen": "\\App\\Models\\MessagesModel\u003A\u003A\u0024returnType",
            "name": "returnType",
            "summary": "",
            "url": "classes/App-Models-MessagesModel.html#property_returnType"
        },                {
            "fqsen": "\\App\\Models\\MessagesModel\u003A\u003A\u0024useSoftDeletes",
            "name": "useSoftDeletes",
            "summary": "",
            "url": "classes/App-Models-MessagesModel.html#property_useSoftDeletes"
        },                {
            "fqsen": "\\App\\Models\\MessagesModel\u003A\u003A\u0024beforeUpdate",
            "name": "beforeUpdate",
            "summary": "",
            "url": "classes/App-Models-MessagesModel.html#property_beforeUpdate"
        },                {
            "fqsen": "\\App\\Models\\MessagesModel\u003A\u003A\u0024afterDelete",
            "name": "afterDelete",
            "summary": "",
            "url": "classes/App-Models-MessagesModel.html#property_afterDelete"
        },                {
            "fqsen": "\\App\\Models\\MessagesModel\u003A\u003A\u0024validationRules",
            "name": "validationRules",
            "summary": "",
            "url": "classes/App-Models-MessagesModel.html#property_validationRules"
        },                {
            "fqsen": "\\App\\Models\\PmpsksImgModel",
            "name": "PmpsksImgModel",
            "summary": "",
            "url": "classes/App-Models-PmpsksImgModel.html"
        },                {
            "fqsen": "\\App\\Models\\PmpsksImgModel\u003A\u003AgetImages\u0028\u0029",
            "name": "getImages",
            "summary": "",
            "url": "classes/App-Models-PmpsksImgModel.html#method_getImages"
        },                {
            "fqsen": "\\App\\Models\\PmpsksImgModel\u003A\u003AdeleteImages\u0028\u0029",
            "name": "deleteImages",
            "summary": "",
            "url": "classes/App-Models-PmpsksImgModel.html#method_deleteImages"
        },                {
            "fqsen": "\\App\\Models\\PmpsksImgModel\u003A\u003A\u0024table",
            "name": "table",
            "summary": "",
            "url": "classes/App-Models-PmpsksImgModel.html#property_table"
        },                {
            "fqsen": "\\App\\Models\\PmpsksImgModel\u003A\u003A\u0024primaryKey",
            "name": "primaryKey",
            "summary": "",
            "url": "classes/App-Models-PmpsksImgModel.html#property_primaryKey"
        },                {
            "fqsen": "\\App\\Models\\PmpsksImgModel\u003A\u003A\u0024allowedFields",
            "name": "allowedFields",
            "summary": "",
            "url": "classes/App-Models-PmpsksImgModel.html#property_allowedFields"
        },                {
            "fqsen": "\\App\\Models\\PmpsksImgModel\u003A\u003A\u0024returnType",
            "name": "returnType",
            "summary": "",
            "url": "classes/App-Models-PmpsksImgModel.html#property_returnType"
        },                {
            "fqsen": "\\App\\Models\\PmpsksImgModel\u003A\u003A\u0024validationRules",
            "name": "validationRules",
            "summary": "",
            "url": "classes/App-Models-PmpsksImgModel.html#property_validationRules"
        },                {
            "fqsen": "\\App\\Models\\PmpsksModel",
            "name": "PmpsksModel",
            "summary": "",
            "url": "classes/App-Models-PmpsksModel.html"
        },                {
            "fqsen": "\\App\\Models\\PmpsksModel\u003A\u003A\u0024table",
            "name": "table",
            "summary": "",
            "url": "classes/App-Models-PmpsksModel.html#property_table"
        },                {
            "fqsen": "\\App\\Models\\PmpsksModel\u003A\u003A\u0024primaryKey",
            "name": "primaryKey",
            "summary": "",
            "url": "classes/App-Models-PmpsksModel.html#property_primaryKey"
        },                {
            "fqsen": "\\App\\Models\\PmpsksModel\u003A\u003A\u0024returnType",
            "name": "returnType",
            "summary": "",
            "url": "classes/App-Models-PmpsksModel.html#property_returnType"
        },                {
            "fqsen": "\\App\\Filters\\SecurityFilter",
            "name": "SecurityFilter",
            "summary": "",
            "url": "classes/App-Filters-SecurityFilter.html"
        },                {
            "fqsen": "\\App\\Filters\\SecurityFilter\u003A\u003Abefore\u0028\u0029",
            "name": "before",
            "summary": "",
            "url": "classes/App-Filters-SecurityFilter.html#method_before"
        },                {
            "fqsen": "\\App\\Filters\\SecurityFilter\u003A\u003Aafter\u0028\u0029",
            "name": "after",
            "summary": "",
            "url": "classes/App-Filters-SecurityFilter.html#method_after"
        },                {
            "fqsen": "\\",
            "name": "\\",
            "summary": "",
            "url": "namespaces/default.html"
        },                {
            "fqsen": "\\App\\Controllers",
            "name": "Controllers",
            "summary": "",
            "url": "namespaces/app-controllers.html"
        },                {
            "fqsen": "\\App",
            "name": "App",
            "summary": "",
            "url": "namespaces/app.html"
        },                {
            "fqsen": "\\App\\Controllers\\Content",
            "name": "Content",
            "summary": "",
            "url": "namespaces/app-controllers-content.html"
        },                {
            "fqsen": "\\App\\Controllers\\Data",
            "name": "Data",
            "summary": "",
            "url": "namespaces/app-controllers-data.html"
        },                {
            "fqsen": "\\App\\Controllers\\User",
            "name": "User",
            "summary": "",
            "url": "namespaces/app-controllers-user.html"
        },                {
            "fqsen": "\\App\\Filters",
            "name": "Filters",
            "summary": "",
            "url": "namespaces/app-filters.html"
        },                {
            "fqsen": "\\App\\Libraries",
            "name": "Libraries",
            "summary": "",
            "url": "namespaces/app-libraries.html"
        },                {
            "fqsen": "\\App\\Models",
            "name": "Models",
            "summary": "",
            "url": "namespaces/app-models.html"
        }            ]
);
